version: "3.3"

services:
        onestopnode:
                build:
                        context: .
                        dockerfile: Dockerfile.prod
                extra_hosts:
                        - "host.docker.internal:host-gateway"
                volumes:
                        - onestoppublic:/home/node/app/public
                        - onestopimages:/home/node/app/images_folder
                        - onestopfiles:/home/node/app/files_folder
                ports:
                        - "9010:9010"
                network_mode:  "common-net"
                env_file:
                        - .env

volumes:
        onestoppublic:
        onestopimages:
        onestopfiles:
