#################
#
#
#
#NOTE STOP THE WORKFLOW AS SOON AS TESTING IS DONE
#TO PREVENT USE OF GITHUB MINUTES
#
#
#
######################
name: JS logs continuos
on:
    workflow_dispatch:

jobs:

  build:
    name: Deploy
    timeout-minutes: 300
    runs-on: ubuntu-latest
    steps:
    - name: Establish connection and deploy
      uses: appleboy/ssh-action@master
      with:
        host: ${{ secrets.SSH_HOST }}
        key: ${{ secrets.SSH_KEY }}
        passphrase: ${{ secrets.SSH_PASSPHRASE }}
        port: ${{ secrets.SSH_PORT }}
        username: ${{ secrets.SSH_USERNAME }}
        script: |
            cd /webapps/one-stop-2021
            cd api/javascript
            echo "#################################### NOTE ##############################

            STOP THE WORKFLOW AS SOON AS THE TESTING IS DONE TO PREVENT USE OF GITHUB MINUTES.
            TRY TO KEEP THE TESTING SHORT
            USE ONE TIME LOGS WORKFLOW RATHER THAN CONTINUOS LOGS FOR ONE-TIME LOGS

            ###########################################################################"
            docker-compose -f docker-compose.prod.yaml logs -f

